"""add_hint_tracking_to_crossword_sessions

Revision ID: 335c95132b72
Revises: dd5f5533ba21
Create Date: 2025-11-15 19:33:14.456087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '335c95132b72'
down_revision: Union[str, None] = 'dd5f5533ba21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crossword_game_sessions', sa.Column('revealed_cells', sa.JSON(), nullable=True))
    op.add_column('crossword_game_sessions', sa.Column('hints_used', sa.Integer(), nullable=False))
    op.add_column('crossword_game_sessions', sa.Column('revealed_all', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crossword_game_sessions', 'revealed_all')
    op.drop_column('crossword_game_sessions', 'hints_used')
    op.drop_column('crossword_game_sessions', 'revealed_cells')
    # ### end Alembic commands ###
