"""create_wordle_tables

Revision ID: 44396027eac6
Revises: 001
Create Date: 2025-11-14 22:04:50.079646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44396027eac6'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wordle_daily_challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('word', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wordle_daily_challenges_date'), 'wordle_daily_challenges', ['date'], unique=True)
    op.create_index(op.f('ix_wordle_daily_challenges_id'), 'wordle_daily_challenges', ['id'], unique=False)
    op.create_table('wordle_game_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('daily_challenge_id', sa.UUID(), nullable=False),
    sa.Column('guesses', sa.JSON(), nullable=False),
    sa.Column('won', sa.Boolean(), nullable=False),
    sa.Column('attempts_used', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['daily_challenge_id'], ['wordle_daily_challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wordle_game_sessions_created_at'), 'wordle_game_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_wordle_game_sessions_daily_challenge_id'), 'wordle_game_sessions', ['daily_challenge_id'], unique=False)
    op.create_index(op.f('ix_wordle_game_sessions_id'), 'wordle_game_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_wordle_game_sessions_user_id'), 'wordle_game_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wordle_game_sessions_user_id'), table_name='wordle_game_sessions')
    op.drop_index(op.f('ix_wordle_game_sessions_id'), table_name='wordle_game_sessions')
    op.drop_index(op.f('ix_wordle_game_sessions_daily_challenge_id'), table_name='wordle_game_sessions')
    op.drop_index(op.f('ix_wordle_game_sessions_created_at'), table_name='wordle_game_sessions')
    op.drop_table('wordle_game_sessions')
    op.drop_index(op.f('ix_wordle_daily_challenges_id'), table_name='wordle_daily_challenges')
    op.drop_index(op.f('ix_wordle_daily_challenges_date'), table_name='wordle_daily_challenges')
    op.drop_table('wordle_daily_challenges')
    # ### end Alembic commands ###
