"""create_crossword_tables

Revision ID: dd5f5533ba21
Revises: 0eb575580d1a
Create Date: 2025-11-15 18:59:58.025889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd5f5533ba21'
down_revision: Union[str, None] = '0eb575580d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crossword_daily_puzzles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('grid_data', sa.JSON(), nullable=False),
    sa.Column('clues_across', sa.JSON(), nullable=False),
    sa.Column('clues_down', sa.JSON(), nullable=False),
    sa.Column('answers_across', sa.JSON(), nullable=False),
    sa.Column('answers_down', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crossword_daily_puzzles_date'), 'crossword_daily_puzzles', ['date'], unique=True)
    op.create_index(op.f('ix_crossword_daily_puzzles_id'), 'crossword_daily_puzzles', ['id'], unique=False)
    op.create_table('crossword_game_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('daily_puzzle_id', sa.UUID(), nullable=False),
    sa.Column('current_grid', sa.JSON(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completion_time_seconds', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['daily_puzzle_id'], ['crossword_daily_puzzles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crossword_game_sessions_created_at'), 'crossword_game_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_crossword_game_sessions_daily_puzzle_id'), 'crossword_game_sessions', ['daily_puzzle_id'], unique=False)
    op.create_index(op.f('ix_crossword_game_sessions_id'), 'crossword_game_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_crossword_game_sessions_user_id'), 'crossword_game_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crossword_game_sessions_user_id'), table_name='crossword_game_sessions')
    op.drop_index(op.f('ix_crossword_game_sessions_id'), table_name='crossword_game_sessions')
    op.drop_index(op.f('ix_crossword_game_sessions_daily_puzzle_id'), table_name='crossword_game_sessions')
    op.drop_index(op.f('ix_crossword_game_sessions_created_at'), table_name='crossword_game_sessions')
    op.drop_table('crossword_game_sessions')
    op.drop_index(op.f('ix_crossword_daily_puzzles_id'), table_name='crossword_daily_puzzles')
    op.drop_index(op.f('ix_crossword_daily_puzzles_date'), table_name='crossword_daily_puzzles')
    op.drop_table('crossword_daily_puzzles')
    # ### end Alembic commands ###
